### ISSUE TITLE
Błąd przy startowaniu samolotów 

### ISSUE THREAD

**Issue by bazylip** [bazylip/ATC#7]
Z nieznanego powodu raz na kilkanaście-kilkadziesiąt przypadków poniższy kod zwraca błąd wyjścia poza zakres listy.  Pogrubiona linijka powodująca błąd.

<pre>
for j in range(len(waitingPlanes[i])):
        if len(waitingPlanes[i]) > 0:
                <b>if waitingPlanes[i][j].id.lower() == command[0]:</b>
</pre>

**Comment by bazylip** [comment]
Pełny tekst błędu

<pre>Traceback (most recent call last):
  File "E:/ATC/main.py", line 760, in <module>
    menu()
  File "E:/ATC/main.py", line 742, in menu
    gameLoop()
  File "E:/ATC/main.py", line 527, in gameLoop
    change(board, commands, waitingPlanes, firstX, firstY, secondX, secondY)
  File "E:/ATC/main.py", line 425, in change
    if waitingPlanes[i][j].id.lower() == command[0]:
IndexError: list index out of range</pre>

**Comment by bazylip** [comment]
Najprawdopodobniej spowodowany przez <pre>command[0]</pre>

**Comment by bazylip** [comment]
Błąd przy starcie samolotu D z jednocześnie oczekującym samolotem F. Dodanie `return` do funkcji, dalsze testy.

<pre>B   b
Correct exit!
Crash!
D   d
Traceback (most recent call last):
F   d
  File "E:/ATC/main.py", line 761, in <module>
    menu()
  File "E:/ATC/main.py", line 743, in menu
    gameLoop()
  File "E:/ATC/main.py", line 528, in gameLoop
    change(board, commands, waitingPlanes, firstX, firstY, secondX, secondY)
  File "E:/ATC/main.py", line 425, in change
    print(waitingPlanes[i][j].id, " ", command[0])
IndexError: list index out of range</pre>

**Comment by bazylip** [comment]
Wygląda, że fixed
